CREATE DATABASE AMP_DATABASE;
USE AMP_DATABASE;
CREATE TABLE USERACC (username VARCHAR(30), password VARCHAR(30));

delimiter $$
CREATE PROCEDURE setUser(IN  username VARCHAR(30),IN  password VARCHAR(30))
	BEGIN
		INSERT INTO USERACC VALUES (username,password);
	END$$
DELIMITER ;

SELECT * FROM USERACC;